name: P1
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch of papaaltay-sokol2007/mihomo"
        required: true
        default: "Alpha"
      upx:
        description: "Compress binaries with UPX"
        type: boolean
        default: true
      version_suffix:
        description: "Version suffix, e.g. -fix-pppoe"
        required: false
        default: ""
      go_version:
        description: "Go version"
        required: false
        default: "1.24.x"
permissions:
  contents: write
jobs:
  build:
    name: Build and release IPK packages
    runs-on: ubuntu-latest
    steps:
      - run: echo hi
