name: S3A
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: echo hello
