name: T2
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch"
        required: true
        default: "Alpha"
jobs:
  t:
    runs-on: ubuntu-latest
    steps:
      - run: echo hi
