name: T9
on:
  workflow_dispatch:
    inputs:
      upx:
        description: "UPX"
        type: boolean
        default: true
      version_suffix:
        description: "Suffix"
        required: false
        default: ""
jobs:
  t:
    runs-on: ubuntu-latest
    steps:
      - run: echo hi
